-- ============================================================
--  AX_Anims - Definición de Animaciones
-- ============================================================

Animations = {}

-- ============================================================
-- EXPRESIONES (Faciales)
-- Dict: facials@gen_male@variations@ / facials@gen_female@variations@
-- ============================================================
Animations.expresiones = {
    { name = "Apuntando",    command = "exp_aiming",      dict = "facials@gen_male@variations@", anim = "mood_aiming_1",             flag = 49, loop = true, prop = nil },
    { name = "Enojado",      command = "exp_angry",       dict = "facials@gen_male@variations@", anim = "mood_angry_1",              flag = 49, loop = true, prop = nil },
    { name = "Quemado",      command = "exp_burning",     dict = "facials@gen_male@variations@", anim = "burning_1",                 flag = 49, loop = true, prop = nil },
    { name = "Muerto",       command = "exp_dead",        dict = "facials@gen_male@variations@", anim = "dead_1",                    flag = 49, loop = true, prop = nil },
    { name = "Borracho",     command = "exp_drunk",       dict = "facials@gen_male@variations@", anim = "mood_drunk_1",              flag = 49, loop = true, prop = nil },
    { name = "Tonto",        command = "exp_dumb",        dict = "facials@gen_male@variations@", anim = "pose_injured_1",            flag = 49, loop = true, prop = nil },
    { name = "Electrocutado",command = "exp_electro",     dict = "facials@gen_male@variations@", anim = "electrocuted_1",            flag = 49, loop = true, prop = nil },
    { name = "Emocionado",   command = "exp_excited",     dict = "facials@gen_male@variations@", anim = "mood_excited_1",            flag = 49, loop = true, prop = nil },
    { name = "Frustrado",    command = "exp_frustrated",  dict = "facials@gen_male@variations@", anim = "mood_frustrated_1",         flag = 49, loop = true, prop = nil },
    { name = "Gruñón",       command = "exp_grumpy",      dict = "facials@gen_male@variations@", anim = "effort_1",                  flag = 49, loop = true, prop = nil },
    { name = "Gruñón 2",     command = "exp_grumpy2",     dict = "facials@gen_male@variations@", anim = "mood_drivefast_1",          flag = 49, loop = true, prop = nil },
    { name = "Gruñón 3",     command = "exp_grumpy3",     dict = "facials@gen_male@variations@", anim = "pose_angry_1",              flag = 49, loop = true, prop = nil },
    { name = "Feliz",        command = "exp_happy",       dict = "facials@gen_male@variations@", anim = "mood_happy_1",              flag = 49, loop = true, prop = nil },
    { name = "Volado",       command = "exp_high",        dict = "facials@gen_male@variations@", anim = "mood_dancing_high_1",       flag = 49, loop = true, prop = nil },
    { name = "Herido",       command = "exp_injured",     dict = "facials@gen_male@variations@", anim = "mood_injured_1",            flag = 49, loop = true, prop = nil },
    { name = "Alegre",       command = "exp_joyful",      dict = "facials@gen_male@variations@", anim = "mood_dancing_low_1",        flag = 49, loop = true, prop = nil },
    { name = "Alegre 2",     command = "exp_joyful2",     dict = "facials@gen_male@variations@", anim = "mood_dancing_low_2",        flag = 49, loop = true, prop = nil },
    { name = "Fumando",      command = "exp_smoke",       dict = "facials@gen_male@variations@", anim = "smoking_hold_1",            flag = 49, loop = true, prop = nil },
    { name = "Sin Parpadear",command = "exp_noblink",     dict = "facials@gen_male@variations@", anim = "pose_normal_1",             flag = 49, loop = true, prop = nil },
    { name = "Un Ojo",       command = "exp_oneeye",      dict = "facials@gen_male@variations@", anim = "pose_aiming_1",             flag = 49, loop = true, prop = nil },
    { name = "Tramando",     command = "exp_scheme",      dict = "facials@gen_male@variations@", anim = "mood_dancing_high_2",       flag = 49, loop = true, prop = nil },
    { name = "Impactado",    command = "exp_shocked",     dict = "facials@gen_male@variations@", anim = "shocked_1",                 flag = 49, loop = true, prop = nil },
    { name = "Impactado 2",  command = "exp_shocked2",    dict = "facials@gen_male@variations@", anim = "shocked_2",                 flag = 49, loop = true, prop = nil },
    { name = "Dormido",      command = "exp_sleeping",    dict = "facials@gen_male@variations@", anim = "mood_sleeping_1",           flag = 49, loop = true, prop = nil },
    { name = "Dormido 2",    command = "exp_sleeping2",   dict = "facials@gen_male@variations@", anim = "dead_1",                    flag = 49, loop = true, prop = nil },
    { name = "Dormido 3",    command = "exp_sleeping3",   dict = "facials@gen_male@variations@", anim = "dead_2",                    flag = 49, loop = true, prop = nil },
    { name = "Engreído",     command = "exp_smug",        dict = "facials@gen_male@variations@", anim = "mood_smug_1",               flag = 49, loop = true, prop = nil },
    { name = "Engreído 2",   command = "exp_smug2",       dict = "facials@gen_male@variations@", anim = "mood_dancing_medium_4",     flag = 49, loop = true, prop = nil },
    { name = "Estresado",    command = "exp_stressed",    dict = "facials@gen_male@variations@", anim = "mood_stressed_1",           flag = 49, loop = true, prop = nil },
    { name = "Hablando",     command = "exp_talking",     dict = "facials@gen_male@variations@", anim = "mood_talking_1",            flag = 49, loop = true, prop = nil },
    { name = "Nervioso",     command = "exp_twitch",      dict = "facials@gen_male@variations@", anim = "mood_skydive_1",            flag = 49, loop = true, prop = nil },
    { name = "Amargado",     command = "exp_sulking",     dict = "facials@gen_male@variations@", anim = "mood_sulk_1",               flag = 49, loop = true, prop = nil },
    { name = "Raro",         command = "exp_weird",       dict = "facials@gen_male@variations@", anim = "effort_2",                  flag = 49, loop = true, prop = nil },
    { name = "Raro 2",       command = "exp_weird2",      dict = "facials@gen_male@variations@", anim = "effort_3",                  flag = 49, loop = true, prop = nil },
    { name = "Raro 3",       command = "exp_weird3",      dict = "facials@gen_male@variations@", anim = "melee_effort_1",            flag = 49, loop = true, prop = nil },
}

-- ============================================================
-- BAILES
-- ============================================================
Animations.bailes = {
    { name = "Dance",              command = "dance",         dict = "anim@amb@nightclub@dancers@podium_dancers@",              anim = "hi_dance_facedj_17_v2_male^5",        flag = 1, loop = true,  prop = nil },
    { name = "Dance 2",            command = "dance2",        dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@",    anim = "high_center_down",                    flag = 1, loop = true,  prop = nil },
    { name = "Dance 3",            command = "dance3",        dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@",    anim = "high_center",                         flag = 1, loop = true,  prop = nil },
    { name = "Dance 4",            command = "dance4",        dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@",    anim = "high_center_up",                      flag = 1, loop = true,  prop = nil },
    { name = "Dance 5",            command = "dance5",        dict = "anim@amb@casino@mini@dance@dance_solo@female@var_a@",     anim = "med_center",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance 6",            command = "dance6",        dict = "misschinese2_crystalmazemcs1_cs",                         anim = "dance_loop_tao",                      flag = 1, loop = true,  prop = nil },
    { name = "Dance 7",            command = "dance7",        dict = "misschinese2_crystalmazemcs1_ig",                         anim = "dance_loop_tao",                      flag = 1, loop = true,  prop = nil },
    { name = "Dance 8",            command = "dance8",        dict = "missfbi3_sniping",                                        anim = "dance_m_default",                     flag = 1, loop = true,  prop = nil },
    { name = "Dance 9",            command = "dance9",        dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@",  anim = "med_center_up",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance F",            command = "dancef",        dict = "anim@amb@nightclub@dancers@solomun_entourage@",           anim = "mi_dance_facedj_17_v1_female^1",      flag = 1, loop = true,  prop = nil },
    { name = "Dance F2",           command = "dancef2",       dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@",  anim = "high_center",                         flag = 1, loop = true,  prop = nil },
    { name = "Dance F3",           command = "dancef3",       dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@",  anim = "high_center_up",                      flag = 1, loop = true,  prop = nil },
    { name = "Dance F4",           command = "dancef4",       dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_female^1",    flag = 1, loop = true,  prop = nil },
    { name = "Dance F5",           command = "dancef5",       dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_female^3",    flag = 1, loop = true,  prop = nil },
    { name = "Dance Club",         command = "danceclub",     dict = "anim@amb@nightclub_island@dancers@beachdance@",           anim = "hi_idle_a_m03",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 2",       command = "danceclubb",    dict = "anim@amb@nightclub_island@dancers@beachdance@",           anim = "hi_idle_a_m05",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 3",       command = "danceclubc",    dict = "anim@amb@nightclub_island@dancers@beachdance@",           anim = "hi_idle_a_m02",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 4",       command = "danceclubd",    dict = "anim@amb@nightclub_island@dancers@beachdance@",           anim = "hi_idle_b_f01",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 5",       command = "danceclube",    dict = "anim@amb@nightclub_island@dancers@club@",                 anim = "hi_idle_a_f02",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 6",       command = "danceclubf",    dict = "anim@amb@nightclub_island@dancers@club@",                 anim = "hi_idle_b_m03",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 7",       command = "danceclubg",    dict = "anim@amb@nightclub_island@dancers@club@",                 anim = "hi_idle_d_f01",                       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 8",       command = "danceclubh",    dict = "anim@amb@nightclub_island@dancers@crowddance_facedj@",    anim = "mi_dance_facedj_17_v2_male^4",        flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 9",       command = "dancecluби",    dict = "anim@amb@nightclub_island@dancers@crowddance_single_props@", anim = "mi_dance_prop_13_v1_male^3",       flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 10",      command = "danceclubj",    dict = "anim@amb@nightclub_island@dancers@crowddance_groups@groupd@", anim = "mi_dance_crowd_13_v2_male^1",     flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 11",      command = "danceclubk",    dict = "anim@amb@nightclub_island@dancers@crowddance_facedj@",    anim = "mi_dance_facedj_15_v2_male^4",        flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 13",      command = "danceclubm",    dict = "anim@amb@nightclub_island@dancers@crowddance_facedj@",    anim = "hi_dance_facedj_hu_15_v2_male^5",     flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 14",      command = "danceclubn",    dict = "anim@amb@nightclub_island@dancers@crowddance_facedj@",    anim = "hi_dance_facedj_hu_17_male^5",        flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 15",      command = "danceclubo",    dict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@",       anim = "high_center",                         flag = 1, loop = true,  prop = nil },
    { name = "Dance Club 16",      command = "danceclubp",    dict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@",       anim = "high_left_down",                      flag = 1, loop = true,  prop = nil },
    { name = "Dance Slow",         command = "danceslow",     dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@",    anim = "low_center",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance Slow 2",       command = "danceslow2",    dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@",  anim = "low_center",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance Slow 3",       command = "danceslow3",    dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@",  anim = "low_center_down",                     flag = 1, loop = true,  prop = nil },
    { name = "Dance Slow 4",       command = "danceslow4",    dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@",  anim = "low_center",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance Upper",        command = "danceupper",    dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@",  anim = "high_center",                         flag = 1, loop = true,  prop = nil },
    { name = "Dance Upper 2",      command = "danceupper2",   dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@",  anim = "high_center_up",                      flag = 1, loop = true,  prop = nil },
    { name = "Dance Shy",          command = "danceshy",      dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@",    anim = "low_center",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance Shy 2",        command = "danceshy2",     dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@",  anim = "low_center_down",                     flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly",        command = "dancesilly",    dict = "special_ped@mountain_dancer@monologue_3@monologue_3a",    anim = "mnt_dnc_buttwag",                     flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 1",      command = "dancesilly1",   dict = "rcmnigel1bnmt_1b",                                        anim = "dance_loop_tyler",                    flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 2",      command = "dancesilly2",   dict = "move_clown@p_m_zero_idles@",                              anim = "fidget_short_dance",                  flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 3",      command = "dancesilly3",   dict = "move_clown@p_m_two_idles@",                               anim = "fidget_short_dance",                  flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 4",      command = "dancesilly4",   dict = "anim@amb@nightclub@lazlow@hi_podium@",                    anim = "danceidle_hi_11_buttwiggle_b_laz",    flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 5",      command = "dancesilly5",   dict = "timetable@tracy@ig_5@idle_a",                             anim = "idle_a",                              flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 6",      command = "dancesilly6",   dict = "timetable@tracy@ig_8@idle_b",                             anim = "idle_d",                              flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 7",      command = "dancesilly7",   dict = "anim@amb@casino@mini@dance@dance_solo@female@var_b@",     anim = "med_center",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 8",      command = "dancesilly8",   dict = "anim@amb@casino@mini@dance@dance_solo@female@var_b@",     anim = "high_center",                         flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 9",      command = "dancesilly9",   dict = "anim@mp_player_intcelebrationfemale@the_woogie",          anim = "the_woogie",                          flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 10",     command = "dancesilly10",  dict = "anim@amb@nightclub@lazlow@hi_podium@",                    anim = "danceidle_hi_17_spiderman_laz",       flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 11",     command = "dancesilly11",  dict = "anim@amb@nightclub@lazlow@hi_podium@",                    anim = "danceidle_mi_11_pointthrust_laz",     flag = 1, loop = true,  prop = nil },
    { name = "Dance Silly 12",     command = "dancesilly12",  dict = "anim@amb@nightclub@lazlow@hi_podium@",                    anim = "danceidle_hi_17_smackthat_laz",       flag = 1, loop = true,  prop = nil },
    { name = "Dance Old",          command = "danceold",      dict = "anim@mp_player_intupperuncle_disco",                      anim = "idle_a",                              flag = 1, loop = true,  prop = nil },
    { name = "Twerk",              command = "twerk",         dict = "switch@trevor@mocks_lapdance",                            anim = "001443_01_trvs_28_idle_stripper",     flag = 1, loop = true,  prop = nil },
    { name = "Lapdance",           command = "lapdance",      dict = "mp_safehouse",                                            anim = "lap_dance_girl",                      flag = 1, loop = false, prop = nil },
    { name = "Lapdance 2",         command = "lapdance2",     dict = "mini@strip_club@private_dance@idle",                      anim = "priv_dance_idle",                     flag = 1, loop = true,  prop = nil },
    { name = "Lapdance 3",         command = "lapdance3",     dict = "mini@strip_club@private_dance@part1",                     anim = "priv_dance_p1",                       flag = 1, loop = true,  prop = nil },
    { name = "Lapdance 4",         command = "lapdance4",     dict = "mini@strip_club@private_dance@part2",                     anim = "priv_dance_p2",                       flag = 1, loop = true,  prop = nil },
    { name = "Lapdance 5",         command = "lapdance5",     dict = "mini@strip_club@private_dance@part3",                     anim = "priv_dance_p3",                       flag = 1, loop = true,  prop = nil },
    { name = "Lapdance 6",         command = "lapdance6",     dict = "oddjobs@assassinate@multi@yachttarget@lapdance",          anim = "yacht_ld_f",                          flag = 1, loop = true,  prop = nil },
    { name = "Salsa Roll",         command = "salsa",         dict = "anim@mp_player_intuppersalsa_roll",                       anim = "idle_a",                              flag = 1, loop = true,  prop = nil },
    { name = "Crank Dat",          command = "dancecrankdat", dict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@",       anim = "high_right_up",                       flag = 1, loop = true,  prop = nil },
    { name = "Crank Dat 2",        command = "dancecrankdat2",dict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@",       anim = "high_right_down",                     flag = 1, loop = true,  prop = nil },
    { name = "Monkey Dance",       command = "dancemonkey",   dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", anim = "high_center",                         flag = 1, loop = true,  prop = nil },
    { name = "Monkey Dance 2",     command = "dancemonkey2",  dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", anim = "high_center_down",                    flag = 1, loop = true,  prop = nil },
    { name = "Monkey Dance 3",     command = "dancemonkey3",  dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", anim = "med_center_down",                     flag = 1, loop = true,  prop = nil },
    { name = "Boxing Dance",       command = "boxdance",      dict = "anim@amb@nightclub@mini@dance@dance_solo@beach_boxing@",  anim = "med_right_down",                      flag = 1, loop = true,  prop = nil },
    { name = "Hip Hop Dance",      command = "dancehiphop",   dict = "anim@amb@nightclub@mini@dance@dance_paired@dance_d@",     anim = "ped_a_dance_idle",                    flag = 1, loop = true,  prop = nil },
    { name = "Hip Hop Dance 2",    command = "dancehiphop2",  dict = "anim@amb@nightclub@mini@dance@dance_paired@dance_b@",     anim = "ped_a_dance_idle",                    flag = 1, loop = true,  prop = nil },
    { name = "Hip Hop Dance 3",    command = "dancehiphop3",  dict = "anim@amb@nightclub@mini@dance@dance_paired@dance_a@",     anim = "ped_a_dance_idle",                    flag = 1, loop = true,  prop = nil },
    { name = "Drill Dance",        command = "dancedrill",    dict = "sdrill@animation",                                        anim = "sdrill_clip",                         flag = 1, loop = true,  prop = nil },
    { name = "Techno Dance",       command = "technodance",   dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", anim = "high_left_up",                        flag = 1, loop = true,  prop = nil },
    { name = "Techno Dance 2",     command = "technodance2",  dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", anim = "med_center_up",                       flag = 1, loop = true,  prop = nil },
    { name = "Techno Dance 3",     command = "technodance3",  dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", anim = "high_left",                           flag = 1, loop = true,  prop = nil },
    { name = "Techno Dance 4",     command = "technodance4",  dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", anim = "high_right_up",                       flag = 1, loop = true,  prop = nil },
    { name = "Zombie Dance",       command = "zompopdance",   dict = "zompop@danceanim",                                        anim = "zompop_clip",                         flag = 1, loop = true,  prop = nil },
    { name = "Wave Dance",         command = "dancewave",     dict = "dancing_wave_part_one@anim",                              anim = "wave_dance_1",                        flag = 1, loop = true,  prop = nil },
    { name = "Wave Dance 2",       command = "dancewave02",   dict = "dancing_wave_part_one@anim",                              anim = "wave_dance_2",                        flag = 1, loop = true,  prop = nil },
    { name = "Wave Dance 3",       command = "dancewave03",   dict = "dancing_wave_part_one@anim",                              anim = "wave_dance_3",                        flag = 1, loop = true,  prop = nil },
    { name = "Wave Dance 4",       command = "dancewave04",   dict = "dancing_wave_part_one@anim",                              anim = "wave_dance_4",                        flag = 1, loop = true,  prop = nil },
    { name = "Tutankhamen",        command = "dancewave05",   dict = "dancing_wave_part_one@anim",                              anim = "tutankhamun_dance_1",                 flag = 1, loop = true,  prop = nil },
    { name = "Tutankhamen 2",      command = "dancewave06",   dict = "dancing_wave_part_one@anim",                              anim = "tutankhamun_dance_2",                 flag = 1, loop = true,  prop = nil },
    { name = "Snake Dance",        command = "dancewave07",   dict = "dancing_wave_part_one@anim",                              anim = "snake_dance_1",                       flag = 1, loop = true,  prop = nil },
    { name = "Slide Dance",        command = "dancewave08",   dict = "dancing_wave_part_one@anim",                              anim = "slide_dance",                         flag = 1, loop = true,  prop = nil },
    { name = "Slide Dance 2",      command = "dancewave09",   dict = "dancing_wave_part_one@anim",                              anim = "slide_dance_2",                       flag = 1, loop = true,  prop = nil },
    { name = "Robot Dance",        command = "dancewave10",   dict = "dancing_wave_part_one@anim",                              anim = "robot_dance",                         flag = 1, loop = true,  prop = nil },
    { name = "Locking Dance",      command = "dancewave11",   dict = "dancing_wave_part_one@anim",                              anim = "locking_dance",                       flag = 1, loop = true,  prop = nil },
    { name = "Headspin",           command = "dancewave12",   dict = "dancing_wave_part_one@anim",                              anim = "headspin",                            flag = 1, loop = false, prop = nil },
    { name = "Flaire Dance",       command = "dancewave13",   dict = "dancing_wave_part_one@anim",                              anim = "flaire_dance",                        flag = 1, loop = false, prop = nil },
    { name = "Female Crowd Dance", command = "dancewave14",   dict = "dancing_wave_part_one@anim",                              anim = "crowd_girl_dance",                    flag = 1, loop = false, prop = nil },
    { name = "Rock Up Dance",      command = "dancewave15",   dict = "dancing_wave_part_one@anim",                              anim = "uprock_dance_1",                      flag = 1, loop = true,  prop = nil },
    { name = "DJ",                 command = "dj",            dict = "anim@amb@nightclub@djs@dixon@",                           anim = "dixn_dance_cntr_open_dix",            flag = 1, loop = true,  prop = nil },
    { name = "DJ 2",               command = "dj2",           dict = "anim@amb@nightclub@djs@solomun@",                         anim = "sol_idle_ctr_mid_a_sol",              flag = 1, loop = true,  prop = nil },
    { name = "DJ 3",               command = "dj3",           dict = "anim@amb@nightclub@djs@solomun@",                         anim = "sol_dance_l_sol",                     flag = 1, loop = true,  prop = nil },
    { name = "DJ 4",               command = "dj4",           dict = "anim@amb@nightclub@djs@black_madonna@",                   anim = "dance_b_idle_a_blamadon",             flag = 1, loop = true,  prop = nil },
    { name = "DJ 5",               command = "dj5",           dict = "anim@amb@nightclub@djs@dixon@",                           anim = "dixn_idle_cntr_a_dix",                flag = 1, loop = true,  prop = nil },
    { name = "DJ 6",               command = "dj6",           dict = "anim@amb@nightclub@djs@dixon@",                           anim = "dixn_idle_cntr_b_dix",                flag = 1, loop = true,  prop = nil },
    { name = "DJ 7",               command = "dj7",           dict = "anim@amb@nightclub@djs@dixon@",                           anim = "dixn_idle_cntr_g_dix",                flag = 1, loop = true,  prop = nil },
    { name = "DJ 8",               command = "dj8",           dict = "anim@amb@nightclub@djs@dixon@",                           anim = "dixn_idle_cntr_gb_dix",               flag = 1, loop = true,  prop = nil },
    { name = "DJ 9",               command = "dj9",           dict = "anim@amb@nightclub@djs@dixon@",                           anim = "dixn_sync_cntr_j_dix",                flag = 1, loop = true,  prop = nil },
    { name = "DJ 10",              command = "dj10",          dict = "mini@strip_club@idles@dj@base",                           anim = "base",                                flag = 1, loop = true,  prop = nil },
    { name = "DJ 11",              command = "dj11",          dict = "mini@strip_club@idles@dj@idle_04",                        anim = "idle_04",                             flag = 1, loop = true,  prop = nil },
    { name = "DJ 12",              command = "dj12",          dict = "mini@strip_club@idles@dj@idle_02",                        anim = "idle_02",                             flag = 1, loop = true,  prop = nil },
    -- Con Props
    { name = "Dance Cerveza",      command = "dancedrink",    dict = "anim@amb@nightclub_island@dancers@beachdanceprop@",        anim = "mi_idle_c_m01",                       flag = 1, loop = true,
        prop = { model = "prop_beer_amopen",              bone = 28422, pos = vector3(0.0, 0.0, 0.0),     rot = vector3(0.0, 0.0, 20.0)  } },
    { name = "Dance Vino",         command = "dancedrink2",   dict = "anim@amb@nightclub_island@dancers@beachdanceprop@",        anim = "mi_loop_f1",                          flag = 1, loop = true,
        prop = { model = "p_wine_glass_s",                bone = 28422, pos = vector3(0.0, 0.0, -0.09),   rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Dance Whisky",       command = "dancedrink3",   dict = "anim@amb@nightclub_island@dancers@beachdanceprop@",        anim = "mi_loop_m04",                         flag = 1, loop = true,
        prop = { model = "ba_prop_battle_whiskey_opaque_s", bone = 28422, pos = vector3(-0.01, 0.0, 0.0), rot = vector3(0.0, 0.0, 10.0)  } },
    { name = "Dance Whisky 2",     command = "dancedrink4",   dict = "anim@amb@nightclub_island@dancers@beachdanceprops@male@",  anim = "mi_idle_b_m04",                       flag = 1, loop = true,
        prop = { model = "ba_prop_battle_whiskey_opaque_s", bone = 28422, pos = vector3(-0.01, 0.0, 0.0), rot = vector3(0.0, 0.0, 10.0)  } },
    { name = "Dance Vino 2",       command = "dancedrink5",   dict = "anim@amb@nightclub_island@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_female^3",      flag = 1, loop = true,
        prop = { model = "p_wine_glass_s",                bone = 28422, pos = vector3(0.0, 0.0, -0.09),   rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Dance Cerveza 2",    command = "dancedrink6",   dict = "anim@amb@nightclub_island@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_male^3",        flag = 1, loop = true,
        prop = { model = "prop_beer_logopen",              bone = 28422, pos = vector3(0.009, 0.001, -0.031), rot = vector3(180.0, 180.0, -70.0) } },
    { name = "Dance Vino 3",       command = "dancedrink7",   dict = "anim@amb@nightclub_island@dancers@crowddance_single_props@", anim = "hi_dance_prop_11_v1_female^3",      flag = 1, loop = true,
        prop = { model = "p_wine_glass_s",                bone = 28422, pos = vector3(0.0, 0.0, -0.09),   rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Dance Vino 4",       command = "dancedrink8",   dict = "anim@amb@nightclub_island@dancers@crowddance_single_props@", anim = "hi_dance_prop_11_v1_female^1",      flag = 1, loop = true,
        prop = { model = "p_wine_glass_s",                bone = 28422, pos = vector3(0.0, 0.0, -0.09),   rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Dance Cerveza 3",    command = "dancedrink9",   dict = "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@",   anim = "med_right_down",                      flag = 1, loop = true,
        prop = { model = "prop_beer_amopen",              bone = 60309, pos = vector3(0.09, -0.2, 0.05),  rot = vector3(-100.0, 0.0, 0.0) } },
    { name = "Dance Caballo",      command = "dancehorse",    dict = "anim@amb@nightclub@lazlow@hi_dancefloor@",                  anim = "dancecrowd_li_15_handup_laz",         flag = 1, loop = true,
        prop = { model = "ba_prop_battle_hobby_horse",    bone = 28422, pos = vector3(0.0, 0.0, 0.0),     rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Dance Caballo 2",    command = "dancehorse2",   dict = "anim@amb@nightclub@lazlow@hi_dancefloor@",                  anim = "crowddance_hi_11_handup_laz",         flag = 1, loop = true,
        prop = { model = "ba_prop_battle_hobby_horse",    bone = 28422, pos = vector3(0.0, 0.0, 0.0),     rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Dance Caballo 3",    command = "dancehorse3",   dict = "anim@amb@nightclub@lazlow@hi_dancefloor@",                  anim = "dancecrowd_li_11_hu_shimmy_laz",      flag = 1, loop = true,
        prop = { model = "ba_prop_battle_hobby_horse",    bone = 28422, pos = vector3(0.0, 0.0, 0.0),     rot = vector3(0.0, 0.0, 0.0)   } },
    { name = "Glowsticks",         command = "danceglowstick",dict = "anim@amb@nightclub@lazlow@hi_railing@",                    anim = "ambclub_13_mi_hi_sexualgriding_laz",  flag = 1, loop = true,
        prop = { model = "ba_prop_battle_glowstick_01",   bone = 28422, pos = vector3(0.07, 0.14, 0.0),   rot = vector3(-80.0, 20.0, 0.0) } },
    { name = "Glowsticks 2",       command = "danceglowstick2",dict = "anim@amb@nightclub@lazlow@hi_railing@",                   anim = "ambclub_12_mi_hi_bootyshake_laz",     flag = 1, loop = true,
        prop = { model = "ba_prop_battle_glowstick_01",   bone = 28422, pos = vector3(0.07, 0.14, 0.0),   rot = vector3(-80.0, 20.0, 0.0) } },
    { name = "Glowsticks 3",       command = "danceglowstick3",dict = "anim@amb@nightclub@lazlow@hi_railing@",                   anim = "ambclub_09_mi_hi_bellydancer_laz",    flag = 1, loop = true,
        prop = { model = "ba_prop_battle_glowstick_01",   bone = 28422, pos = vector3(0.07, 0.14, 0.0),   rot = vector3(-80.0, 20.0, 0.0) } },
}

-- ============================================================
-- FORMAS DE CAMINAR (Walkstyles)
-- ============================================================
Animations.caminar = {
    { name = "Normal",           command = "walk_normal",       walkstyle = ""                                  },
    { name = "Alien",            command = "walk_alien",        walkstyle = "move_m@alien"                      },
    { name = "Armado",           command = "walk_armored",      walkstyle = "anim_group_move_ballistic"         },
    { name = "Arrogante",        command = "walk_arrogant",     walkstyle = "move_f@arrogant@a"                 },
    { name = "Butch",            command = "walk_butch",        walkstyle = "move_m@hurry_butch@a"              },
    { name = "Butch 2",          command = "walk_butch2",       walkstyle = "move_m@hurry_butch@b"              },
    { name = "Butch 3",          command = "walk_butch3",       walkstyle = "move_m@hurry_butch@c"              },
    { name = "Achispado",        command = "walk_buzzed",       walkstyle = "move_m@buzzed"                     },
    { name = "Valiente",         command = "walk_brave",        walkstyle = "move_m@brave"                      },
    { name = "Valiente 2",       command = "walk_brave2",       walkstyle = "move_m@brave@a"                    },
    { name = "Valiente 3",       command = "walk_brave3",       walkstyle = "move_m@brave@b"                    },
    { name = "Casey",            command = "walk_casey",        walkstyle = "move_casey"                        },
    { name = "Casual",           command = "walk_casual",       walkstyle = "move_m@casual@a"                   },
    { name = "Casual 2",         command = "walk_casual2",      walkstyle = "move_m@casual@b"                   },
    { name = "Casual 3",         command = "walk_casual3",      walkstyle = "move_m@casual@c"                   },
    { name = "Casual 4",         command = "walk_casual4",      walkstyle = "move_m@casual@d"                   },
    { name = "Casual 5",         command = "walk_casual5",      walkstyle = "move_m@casual@e"                   },
    { name = "Casual 6",         command = "walk_casual6",      walkstyle = "move_m@casual@f"                   },
    { name = "Chichi",           command = "walk_chichi",       walkstyle = "move_f@chichi"                     },
    { name = "Seguro",           command = "walk_confident",    walkstyle = "move_m@confident"                  },
    { name = "Policía",          command = "walk_cop",          walkstyle = "move_m@business@a"                 },
    { name = "Policía 2",        command = "walk_cop2",         walkstyle = "move_m@business@b"                 },
    { name = "Policía 3",        command = "walk_cop3",         walkstyle = "move_m@business@c"                 },
    { name = "Cobarde",          command = "walk_coward",       walkstyle = "move_m@coward"                     },
    { name = "Gordo M",          command = "walk_chubby",       walkstyle = "move_chubby"                       },
    { name = "Gordo F",          command = "walk_chubbyfem",    walkstyle = "move_f@chubby@a"                   },
    { name = "Dave",             command = "walk_dave",         walkstyle = "move_characters@dave_n"            },
    { name = "Femenino",         command = "walk_female",       walkstyle = "move_f@multiplayer"                },
    { name = "Masculino",        command = "walk_male",         walkstyle = "move_m@multiplayer"                },
    { name = "Deprimido",        command = "walk_depressed",    walkstyle = "move_m@depressed@a"                },
    { name = "Deprimido 2",      command = "walk_depressed2",   walkstyle = "move_m@depressed@b"                },
    { name = "Deprimido 3",      command = "walk_depressed3",   walkstyle = "move_f@depressed@a"                },
    { name = "Deprimido 4",      command = "walk_depressed4",   walkstyle = "move_f@depressed@c"                },
    { name = "Borracho",         command = "walk_drunk",        walkstyle = "move_m@drunk@a"                    },
    { name = "Borracho 2",       command = "walk_drunk2",       walkstyle = "move_m@buzzed"                     },
    { name = "Borracho 3",       command = "walk_drunk3",       walkstyle = "move_m@drunk@moderatedrunk"        },
    { name = "Borracho 4",       command = "walk_drunk4",       walkstyle = "move_m@drunk@moderatedrunk_head_up"},
    { name = "Borracho 5",       command = "walk_drunk5",       walkstyle = "move_m@drunk@slightlydrunk"        },
    { name = "Muy Borracho",     command = "walk_verydrunk",    walkstyle = "move_m@drunk@verydrunk"            },
    { name = "Gordo 1",          command = "walk_fat",          walkstyle = "move_m@fat@a"                      },
    { name = "Gordo 2",          command = "walk_fat2",         walkstyle = "move_f@fat@a"                      },
    { name = "Gordo 3",          command = "walk_fat3",         walkstyle = "move_m@fat@bulky"                  },
    { name = "Femenino 2",       command = "walk_femme",        walkstyle = "move_f@femme@"                     },
    { name = "Femenino 3",       command = "walk_femme2",       walkstyle = "move_m@femme@"                     },
    { name = "Floyd",            command = "walk_floyd",        walkstyle = "move_characters@floyd"             },
    { name = "Franklin",         command = "walk_franklin",     walkstyle = "move_p_m_one"                      },
    { name = "Gangster",         command = "walk_gangster",     walkstyle = "move_m@gangster@generic"           },
    { name = "Gangster 2",       command = "walk_gangster2",    walkstyle = "move_gangster"                     },
    { name = "Gangster 3",       command = "walk_gangster3",    walkstyle = "move_m@gangster@ng"                },
    { name = "Gangster 4",       command = "walk_gangster4",    walkstyle = "move_m@gangster@var_a"             },
    { name = "Gangster 5",       command = "walk_gangster5",    walkstyle = "move_m@gangster@var_b"             },
    { name = "Gangster 6",       command = "walk_gangster6",    walkstyle = "move_m@gangster@var_c"             },
    { name = "Gangster 7",       command = "walk_gangster7",    walkstyle = "move_m@gangster@var_d"             },
    { name = "Gangster 8",       command = "walk_gangster8",    walkstyle = "move_m@gangster@var_e"             },
    { name = "Gangster 9",       command = "walk_gangster9",    walkstyle = "move_m@gangster@var_f"             },
    { name = "Gangster 10",      command = "walk_gangster10",   walkstyle = "move_m@gangster@var_g"             },
    { name = "Gangster 11",      command = "walk_gangster11",   walkstyle = "move_m@gangster@var_h"             },
    { name = "Gangster 12",      command = "walk_gangster12",   walkstyle = "move_m@gangster@var_i"             },
    { name = "Gangster 13",      command = "walk_gangster13",   walkstyle = "move_m@gangster@var_j"             },
    { name = "Gangster 14",      command = "walk_gangster14",   walkstyle = "move_m@gangster@var_k"             },
    { name = "Genérico M",       command = "walk_generic",      walkstyle = "move_m@generic"                    },
    { name = "Genérico F",       command = "walk_generic2",     walkstyle = "move_f@generic"                    },
    { name = "Grooving M",       command = "walk_grooving",     walkstyle = "anim@move_m@grooving@"             },
    { name = "Grooving F",       command = "walk_grooving2",    walkstyle = "anim@move_f@grooving@"             },
    { name = "Guardia",          command = "walk_guard",        walkstyle = "move_m@prison_gaurd"               },
    { name = "Esposado",         command = "walk_cuffed",       walkstyle = "move_m@prisoner_cuffed"            },
    { name = "Tacones",          command = "walk_heels",        walkstyle = "move_f@heels@c"                    },
    { name = "Tacones 2",        command = "walk_heels2",       walkstyle = "move_f@heels@d"                    },
    { name = "Senderismo M",     command = "walk_hiking",       walkstyle = "move_m@hiking"                     },
    { name = "Senderismo F",     command = "walk_hiking2",      walkstyle = "move_f@hiking"                     },
    { name = "Hipster",          command = "walk_hipster",      walkstyle = "move_m@hipster@a"                  },
    { name = "Vagabundo",        command = "walk_hobo",         walkstyle = "move_m@hobo@a"                     },
    { name = "Vagabundo 2",      command = "walk_hobo2",        walkstyle = "move_m@hobo@b"                     },
    { name = "Apurado M",        command = "walk_hurry",        walkstyle = "move_m@hurry@a"                    },
    { name = "Apurado F",        command = "walk_hurry2",       walkstyle = "move_f@hurry@a"                    },
    { name = "Herido",           command = "walk_injured",      walkstyle = "move_m@injured"                    },
    { name = "Herido F",         command = "walk_injured2",     walkstyle = "move_f@injured"                    },
    { name = "Intimidación",     command = "walk_intimidation", walkstyle = "move_m@intimidation@1h"            },
    { name = "Intimidación 2",   command = "walk_intimidation2",walkstyle = "move_m@intimidation@cop@unarmed"   },
    { name = "Intimidación 3",   command = "walk_intimidation3",walkstyle = "move_m@intimidation@unarmed"       },
    { name = "Conserje",         command = "walk_janitor",      walkstyle = "move_p_m_zero_janitor"             },
    { name = "Jimmy",            command = "walk_jimmy",        walkstyle = "move_characters@jimmy"             },
    { name = "Trote",            command = "walk_jog",          walkstyle = "move_m@jog@"                       },
    { name = "Lamar",            command = "walk_lamar",        walkstyle = "move_characters@lamar"             },
    { name = "Lester",           command = "walk_lester",       walkstyle = "move_heist_lester"                 },
    { name = "Seductor F",       command = "walk_maneater",     walkstyle = "move_f@maneater"                   },
    { name = "Michael",          command = "walk_michael",      walkstyle = "move_ped_bucket"                   },
    { name = "Dinero",           command = "walk_money",        walkstyle = "move_m@money"                      },
    { name = "Musculoso",        command = "walk_muscle",       walkstyle = "move_m@muscle@a"                   },
    { name = "Nervioso",         command = "walk_nervous",      walkstyle = "move_characters@jimmy@nervous@"    },
    { name = "Patricia",         command = "walk_patricia",     walkstyle = "move_characters@patricia"          },
    { name = "Paramédico",       command = "walk_paramedic",    walkstyle = "move_paramedic"                    },
    { name = "Elegante M",       command = "walk_posh",         walkstyle = "move_m@posh@"                      },
    { name = "Elegante F",       command = "walk_posh2",        walkstyle = "move_f@posh@"                      },
    { name = "Rápido",           command = "walk_quick",        walkstyle = "move_m@quick"                      },
    { name = "Ron",              command = "walk_ron",          walkstyle = "move_characters@ron"               },
    { name = "Triste M",         command = "walk_sad",          walkstyle = "move_m@sad@a"                      },
    { name = "Triste M 2",       command = "walk_sad2",         walkstyle = "move_m@sad@b"                      },
    { name = "Triste M 3",       command = "walk_sad3",         walkstyle = "move_m@sad@c"                      },
    { name = "Triste F",         command = "walk_sad4",         walkstyle = "move_f@sad@a"                      },
    { name = "Triste F 2",       command = "walk_sad5",         walkstyle = "move_f@sad@b"                      },
    { name = "Descarado M",      command = "walk_sassy",        walkstyle = "move_m@sassy"                      },
    { name = "Descarado F",      command = "walk_sassy2",       walkstyle = "move_f@sassy"                      },
    { name = "Asustado",         command = "walk_scared",       walkstyle = "move_f@scared"                     },
    { name = "Sexy",             command = "walk_sexy",         walkstyle = "move_f@sexy@a"                     },
    { name = "Sospechoso",       command = "walk_shady",        walkstyle = "move_m@shadyped@a"                 },
    { name = "Lento",            command = "walk_slow",         walkstyle = "move_characters@jimmy@slow@"       },
    { name = "Stripper",         command = "walk_stripper",     walkstyle = "move_f@stripper@a"                 },
    { name = "Swagger",          command = "walk_swagger",      walkstyle = "move_m@swagger"                    },
    { name = "Swagger 2",        command = "walk_swagger2",     walkstyle = "move_m@swagger@b"                  },
    { name = "Tenso",            command = "walk_tense",        walkstyle = "move_action@generic@core"          },
    { name = "Rudo M",           command = "walk_tough",        walkstyle = "move_m@tough_guy@"                 },
    { name = "Rudo F",           command = "walk_tough2",       walkstyle = "move_f@tough_guy@"                 },
    { name = "Cinturón M",       command = "walk_toolbelt",     walkstyle = "move_m@tool_belt@a"                },
    { name = "Cinturón F",       command = "walk_toolbelt2",    walkstyle = "move_f@tool_belt@a"                },
    { name = "Basura",           command = "walk_trash",        walkstyle = "clipset@move@trash_fast_turn"      },
    { name = "Tracey",           command = "walk_tracey",       walkstyle = "move_characters@tracey"            },
    { name = "Trevor",           command = "walk_trevor",       walkstyle = "move_p_m_two"                      },
    { name = "Muy Lento",        command = "walk_veryslow",     walkstyle = "move_m@leaf_blower"                },
    { name = "Ancho",            command = "walk_wide",         walkstyle = "move_m@bag"                        },
    { name = "Zombie",           command = "walk_zombie",       walkstyle = "clipset@anim@ingame@move_m@zombie@core" },
}

-- ============================================================
-- COMPARTIDAS (2 jugadores)
-- ============================================================
Animations.compartidas = {
    { name = "Handshake",          command = "handshake",      dict1 = "mp_ped_interaction",                       anim1 = "handshake_guy_a",              dict2 = "mp_ped_interaction",                       anim2 = "handshake_guy_b",              flag = 1,  loop = false },
    { name = "Abrazo",             command = "hug",            dict1 = "mp_ped_interaction",                       anim1 = "kisses_guy_a",                 dict2 = "mp_ped_interaction",                       anim2 = "kisses_guy_b",                 flag = 1,  loop = false },
    { name = "Abrazo Romántico",   command = "hugr",           dict1 = "misscarsteal2chad_goodbye",                anim1 = "chad_armsaround_chad",         dict2 = "misscarsteal2chad_goodbye",                anim2 = "chad_armsaround_girl",         flag = 1,  loop = true  },
    { name = "Bro",                command = "bro",            dict1 = "mp_ped_interaction",                       anim1 = "hugs_guy_a",                   dict2 = "mp_ped_interaction",                       anim2 = "hugs_guy_b",                   flag = 1,  loop = false },
    { name = "Dar Objeto",         command = "give",           dict1 = "mp_common",                               anim1 = "givetake1_a",                  dict2 = "mp_common",                               anim2 = "givetake1_b",                  flag = 1,  loop = false },
    { name = "Baseball",           command = "baseball",       dict1 = "anim@arena@celeb@flat@paired@no_props@",   anim1 = "baseball_a_player_a",          dict2 = "anim@arena@celeb@flat@paired@no_props@",   anim2 = "baseball_a_player_b",          flag = 1,  loop = false },
    { name = "Asaltar",            command = "stickup",        dict1 = "random@countryside_gang_fight",            anim1 = "biker_02_stickup_loop",        dict2 = "missminuteman_1ig_2",                      anim2 = "handsup_base",                 flag = 1,  loop = true  },
    { name = "Puñetazo",           command = "punch",          dict1 = "melee@unarmed@streamed_variations",        anim1 = "plyr_takedown_rear_lefthook",  dict2 = "melee@unarmed@streamed_variations",        anim2 = "victim_takedown_front_cross_r", flag = 1, loop = false },
    { name = "Cabezazo",           command = "headbutt",       dict1 = "melee@unarmed@streamed_variations",        anim1 = "plyr_takedown_front_headbutt", dict2 = "melee@unarmed@streamed_variations",        anim2 = "victim_takedown_front_headbutt", flag = 1,loop = false },
    { name = "Bofetada",           command = "slap",           dict1 = "melee@unarmed@streamed_variations",        anim1 = "plyr_takedown_front_slap",     dict2 = "melee@unarmed@streamed_variations",        anim2 = "victim_takedown_front_slap",   flag = 1,  loop = false },
    { name = "Bofetada 2",         command = "slap2",          dict1 = "melee@unarmed@streamed_variations",        anim1 = "plyr_takedown_front_backslap", dict2 = "melee@unarmed@streamed_variations",        anim2 = "victim_takedown_front_backslap",flag = 1, loop = false },
    { name = "Cargar",             command = "carry",          dict1 = "missfinale_c2mcs_1",                       anim1 = "fin_c2_mcs_1_camman",          dict2 = "nm",                                       anim2 = "firemans_carry",               flag = 1,  loop = true  },
    { name = "Cargar 2",           command = "carry3",         dict1 = "anim@heists@box_carry@",                   anim1 = "idle",                         dict2 = "amb@code_human_in_car_idles@generic@ps@base", anim2 = "base",                    flag = 1,  loop = true  },
    { name = "CPR",                command = "cprs",           dict1 = "mini@cpr@char_a@cpr_str",                  anim1 = "cpr_pumpchest",                dict2 = "mini@cpr@char_b@cpr_str",                  anim2 = "cpr_pumpchest",                flag = 1,  loop = true  },
    { name = "CPR 2",              command = "cprs3",          dict1 = "missheistfbi3b_ig8_2",                     anim1 = "cpr_loop_paramedic",           dict2 = "missheistfbi3b_ig8_2",                     anim2 = "cpr_loop_victim",              flag = 1,  loop = true  },
    { name = "Rehén",              command = "hostage",        dict1 = "anim@gangops@hostage@",                    anim1 = "perp_idle",                    dict2 = "anim@gangops@hostage@",                    anim2 = "victim_idle",                  flag = 1,  loop = true  },
    { name = "Besarse",            command = "kiss",           dict1 = "hs3_ext-20",                              anim1 = "cs_lestercrest_3_dual-20",     dict2 = "hs3_ext-20",                              anim2 = "csb_georginacheng_dual-20",    flag = 1,  loop = false },
    { name = "Besarse 2",          command = "kiss3",          dict1 = "hs3_ext-19",                              anim1 = "cs_lestercrest_3_dual-19",     dict2 = "hs3_ext-19",                              anim2 = "csb_georginacheng_dual-19",    flag = 1,  loop = false },
    { name = "Abrazar Pose",       command = "hugpose",        dict1 = "amnilka@photopose@couple@couplefirst",     anim1 = "amnilka_couple_mal_001",       dict2 = "amnilka@photopose@couple@couplefirst",     anim2 = "amnilka_couple_fem_001",       flag = 1,  loop = true  },
    { name = "Cargar Cute",        command = "carrymecute",    dict1 = "amnilka@photopose@couple@couplefirst",     anim1 = "amnilka_couple_mal_002",       dict2 = "amnilka@photopose@couple@couplefirst",     anim2 = "amnilka_couple_fem_002",       flag = 1,  loop = true  },
    { name = "Sentarse Juntos",    command = "sitwithme",      dict1 = "amnilka@photopose@couple@couplefirst",     anim1 = "amnilka_couple_mal_003",       dict2 = "amnilka@photopose@couple@couplefirst",     anim2 = "amnilka_couple_fem_003",       flag = 1,  loop = true  },
    { name = "Foto Cute",          command = "cutepicpose",    dict1 = "amnilka@photopose@couple@couplefirst",     anim1 = "amnilka_couple_mal_004",       dict2 = "amnilka@photopose@couple@couplefirst",     anim2 = "amnilka_couple_fem_004",       flag = 1,  loop = true  },
    { name = "Corazón Manos",      command = "couplehhands",   dict1 = "amnilka@photopose@couple@couplefirst",     anim1 = "amnilka_couple_mal_005",       dict2 = "amnilka@photopose@couple@couplefirst",     anim2 = "amnilka_couple_fem_005",       flag = 1,  loop = true  },
    { name = "Cargar a Cuestas",   command = "pback",          dict1 = "mx@piggypack_a",                          anim1 = "mxclip_a",                     dict2 = "mx@piggypack_b",                          anim2 = "mxanim_b",                    flag = 1,  loop = true  },
    { name = "BFF Pose",           command = "bff",            dict1 = "anim@male_couple_03_b",                   anim1 = "m_couple_03_b_clip",           dict2 = "anim@female_couple_03_b",                 anim2 = "f_couple_03_b_clip",          flag = 1,  loop = true  },
    { name = "Hold Me",            command = "holdme",         dict1 = "mx_couple5_1_a",                          anim1 = "mx_couple5_1_a_clip",          dict2 = "mx_couple5_1_b",                          anim2 = "mx_couple5_1_b_clip",         flag = 1,  loop = true  },
    { name = "Hold Me 2",          command = "holdmec",        dict1 = "mx_couple5_2_a",                          anim1 = "mx_couple5_2_a_clip",          dict2 = "mx_couple5_2_b",                          anim2 = "mx_couple5_2_b_clip",         flag = 1,  loop = true  },
    { name = "Hold Me 3",          command = "holdmee",        dict1 = "mx_couple5_3_a",                          anim1 = "mx_couple5_3_a_clip",          dict2 = "mx_couple5_3_b",                          anim2 = "mx_couple5_3_b_clip",         flag = 1,  loop = true  },
}

-- ============================================================
-- TRABAJO
-- ============================================================
Animations.trabajo = {
    {
        name     = "Escri­bir",
        command  = "write",
        dict     = "anim@amb@office@tasks@computer@",
        anim     = "idle_d",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Teléfono",
        command  = "phone",
        dict     = "cellphone@",
        anim     = "cellphone_text_read_base",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Llamada",
        command  = "call",
        dict     = "cellphone@",
        anim     = "cellphone_call_listen_base",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Mecánico",
        command  = "mechanic",
        dict     = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@",
        anim     = "machinic_loop_mechandude",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Médico",
        command  = "medic",
        dict     = "anim@amb@medic@",
        anim     = "idle_a",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Policía",
        command  = "police",
        dict     = "amb@world_human_cop_idles@male@idle_a",
        anim     = "idle_b",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Barrer",
        command  = "sweep",
        dict     = "amb@world_human_janitor@male@idle_a",
        anim     = "idle_a",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Cargar Caja",
        command  = "carrybox",
        dict     = "anim@heists@box_carry@",
        anim     = "idle",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Soldadura",
        command  = "weld",
        dict     = "anim@amb@ship@",
        anim     = "idle_d",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
    {
        name     = "Pintar",
        command  = "paint",
        dict     = "anim@amb@casino@valet_scenario@",
        anim     = "valet_idle_a",
        flag     = 1,
        loop     = true,
        prop     = nil
    },
}

-- ============================================================
-- PROPS
-- ============================================================
Animations.props = {
    { name = "Paraguas",          command = "umbrella",        dict = "amb@world_human_drinking@coffee@male@base",      anim = "base",               flag = 1, loop = true,
        prop = { model = "p_amb_brolly_01",       bone = 28422, pos = vector3(0.0, 0.02, -0.036),  rot = vector3(0.0, 10.0, 0.0)    } },
    { name = "Paraguas 2",        command = "umbrella2",       dict = "rcmnigel1d",                                     anim = "base_club_shoulder",  flag = 1, loop = true,
        prop = { model = "p_amb_brolly_01",       bone = 28422, pos = vector3(0.07, 0.01, 0.11),   rot = vector3(2.34, -150.96, 57.34) } },
    { name = "Bloc de Notas",     command = "notepad",         dict = "missheistdockssetup1clipboard@base",             anim = "base",               flag = 1, loop = true,
        prop = { model = "prop_notepad_01",       bone = 18905, pos = vector3(0.1, 0.02, 0.05),    rot = vector3(10.0, 0.0, 0.0)    } },
    { name = "Caja",              command = "box",             dict = "anim@heists@box_carry@",                         anim = "idle",               flag = 1, loop = true,
        prop = { model = "hei_prop_heist_box",    bone = 60309, pos = vector3(0.025, 0.08, 0.255), rot = vector3(-145.0, 290.0, 0.0) } },
    { name = "Mazo",              command = "mallet",          dict = "amb@world_human_hammering@male@base",            anim = "base",               flag = 1, loop = true,
        prop = { model = "prop_tool_mallet",      bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Sierra Craneal",    command = "cranialsaw",      dict = "anim@heists@fleeca_bank@drilling",               anim = "drill_straight_end", flag = 1, loop = true,
        prop = { model = "prop_cranial_saw",      bone = 28422, pos = vector3(0.0, 0.0, 0.05),     rot = vector3(90.0, 0.0, 90.0)   } },
    { name = "Pistola de Clavos", command = "nailgun",         dict = "anim@heists@fleeca_bank@drilling",               anim = "drill_straight_end", flag = 1, loop = true,
        prop = { model = "prop_tool_nailgun",     bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 90.0)    } },
    { name = "Extintor",          command = "extinguisher",    dict = "amb@lo_res_idles@",                              anim = "world_human_musician_bongos_lo_res_base", flag = 1, loop = true,
        prop = { model = "prop_fire_exting_1a",   bone = 28422, pos = vector3(0.15, 0.14, -0.52),  rot = vector3(179.79, -178.60, 4.60) } },
    { name = "Bastón Twirl",      command = "batontwirl",      dict = "anim@mp_player_intuppermale@baton_twirl",        anim = "idle_a",             flag = 1, loop = true,
        prop = { model = "w_me_nightstick",       bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Rosa",              command = "rose",            dict = "anim@heists@humane_labs@finale@keycards",        anim = "ped_a_enter_loop",   flag = 1, loop = true,
        prop = { model = "prop_single_rose",      bone = 18905, pos = vector3(0.13, 0.15, 0.0),    rot = vector3(-100.0, 0.0, -20.0) } },
    { name = "Jeringa",           command = "syringe",         dict = "anim@heists@humane_labs@finale@keycards",        anim = "ped_a_enter_loop",   flag = 1, loop = true,
        prop = { model = "prop_syringe_01",       bone = 18905, pos = vector3(0.11, 0.03, 0.01),   rot = vector3(90.0, 0.0, -50.0)  } },
    { name = "Bisturí",           command = "scalpel",         dict = "anim@heists@humane_labs@finale@keycards",        anim = "ped_a_enter_loop",   flag = 1, loop = true,
        prop = { model = "prop_scalpel",          bone = 18905, pos = vector3(0.11, 0.03, 0.01),   rot = vector3(0.0, 180.0, -70.0) } },
    { name = "Sierra de Hueso",   command = "bonesaw",         dict = "anim@heists@humane_labs@finale@keycards",        anim = "ped_a_enter_loop",   flag = 1, loop = true,
        prop = { model = "prop_bonesaw",          bone = 18905, pos = vector3(0.11, 0.03, 0.01),   rot = vector3(0.0, 180.0, -10.0) } },
    { name = "Billete",           command = "dollar",          dict = "anim@heists@humane_labs@finale@keycards",        anim = "ped_a_enter_loop",   flag = 1, loop = true,
        prop = { model = "p_banknote_onedollar_s",bone = 60309, pos = vector3(-0.002, -0.003, 0.032), rot = vector3(82.24, -106.97, 1.37) } },
    { name = "Quitar Casco",      command = "maskup",          dict = "anim@mp_helmets@on_foot",                        anim = "visor_up",           flag = 1, loop = false, prop = nil },
    { name = "Poner Casco",       command = "maskdown",        dict = "anim@mp_helmets@on_foot",                        anim = "visor_down",         flag = 1, loop = false, prop = nil },
    { name = "Quitar Máscara",    command = "masktakeoff",     dict = "anim@scripted@bty5@ig1_intimidate_actor@female_heeled@", anim = "mask_action_b", flag = 1, loop = false, prop = nil },
    { name = "Ajustar Bolsa",     command = "adjustbag",       dict = "amb@world_human_hiker_standing@male@idle_a",     anim = "idle_b",             flag = 1, loop = false, prop = nil },
    { name = "Panel Control",     command = "adjustpanel",     dict = "anim@scripted@heist@ig9_control_tower@male@",    anim = "loop",               flag = 1, loop = true,  prop = nil },
    { name = "Fumar 2",           command = "smoke2",          dict = "amb@world_human_aa_smoke@male@idle_a",           anim = "idle_c",             flag = 1, loop = true,
        prop = { model = "ng_proc_cigarette01a",  bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Fumar 3",           command = "smoke3",          dict = "amb@world_human_aa_smoke@male@idle_a",           anim = "idle_b",             flag = 1, loop = true,
        prop = { model = "ng_proc_cigarette01a",  bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Fumar 4",           command = "smoke4",          dict = "amb@world_human_smoking@female@idle_a",          anim = "idle_b",             flag = 1, loop = true,
        prop = { model = "ng_proc_cigarette01a",  bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Fumar 6",           command = "smoke6",          dict = "anim@amb@carmeet@checkout_car@",                 anim = "smoke_male_a_idle_b", flag = 1, loop = true,
        prop = { model = "ng_proc_cigarette01a",  bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Vape",              command = "vape",            dict = "amb@world_human_smoking@male@male_b@base",       anim = "base",               flag = 1, loop = true,
        prop = { model = "ba_prop_battle_vape_01",bone = 28422, pos = vector3(-0.029, 0.007, -0.005), rot = vector3(91.0, 270.0, -360.0) } },
    { name = "Vape 2",            command = "vape2",           dict = "amb@world_human_smoking@male@male_b@base",       anim = "base",               flag = 1, loop = true,
        prop = { model = "xm3_prop_xm3_vape_01a", bone = 28422, pos = vector3(-0.02, -0.02, 0.02),  rot = vector3(58.0, 110.0, 10.0) } },
    { name = "Bong",              command = "bong",            dict = "anim@safehouse@bong",                            anim = "bong_stage3",        flag = 1, loop = true,
        prop = { model = "prop_bong_01",          bone = 18905, pos = vector3(0.10, -0.25, 0.0),    rot = vector3(95.0, 190.0, 180.0) } },
    { name = "Bong 2",            command = "bong2",           dict = "anim@safehouse@bong",                            anim = "bong_stage3",        flag = 1, loop = true,
        prop = { model = "xm3_prop_xm3_bong_01a", bone = 18905, pos = vector3(0.10, -0.25, 0.0),   rot = vector3(95.0, 190.0, 180.0) } },
    { name = "Pesca 1",           command = "fishing1",        dict = "amb@world_human_stand_fishing@idle_a",           anim = "idle_a",             flag = 1, loop = true,
        prop = { model = "prop_fishing_rod_01",   bone = 60309, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Pesca 2",           command = "fishing2",        dict = "amb@world_human_stand_fishing@idle_a",           anim = "idle_b",             flag = 1, loop = true,
        prop = { model = "prop_fishing_rod_01",   bone = 60309, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Pesca 3",           command = "fishing3",        dict = "amb@world_human_stand_fishing@idle_a",           anim = "idle_c",             flag = 1, loop = true,
        prop = { model = "prop_fishing_rod_01",   bone = 60309, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Maleta",            command = "suitcase",        dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "prop_ld_suitcase_01",   bone = 57005, pos = vector3(0.35, 0.0, 0.0),     rot = vector3(0.0, 266.0, 90.0)  } },
    { name = "Maleta 2",          command = "suitcase2",       dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "prop_security_case_01", bone = 57005, pos = vector3(0.13, 0.0, -0.01),   rot = vector3(0.0, 280.0, 90.0)  } },
    { name = "Boombox",           command = "boombox",         dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "prop_boombox_01",       bone = 57005, pos = vector3(0.27, 0.0, 0.0),     rot = vector3(0.0, 263.0, 58.0)  } },
    { name = "Caja Herramientas", command = "toolbox",         dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "prop_tool_box_04",      bone = 28422, pos = vector3(0.396, 0.041, -0.003), rot = vector3(-90.0, 0.0, 90.0) } },
    { name = "Caja Herr. 2",      command = "toolbox2",        dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "imp_prop_tool_box_01a", bone = 28422, pos = vector3(0.37, 0.02, 0.0),    rot = vector3(90.0, 0.0, -90.0)  } },
    { name = "Caja Herr. 3",      command = "toolbox3",        dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "xm3_prop_xm3_tool_box_01a", bone = 28422, pos = vector3(0.37, 0.02, 0.0), rot = vector3(90.0, 0.0, -90.0) } },
    { name = "Caja Herr. 4",      command = "toolbox4",        dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "xm3_prop_xm3_tool_box_02a", bone = 28422, pos = vector3(0.37, 0.02, 0.0), rot = vector3(90.0, 0.0, -90.0) } },
    { name = "Caja de Dinero",    command = "cashbox",         dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "m23_1_prop_m31_cashbox_01a", bone = 28422, pos = vector3(0.055, 0.009, -0.01), rot = vector3(90.0, 0.0, -81.0) } },
    { name = "Bolsa Basura",      command = "gbag",            dict = "missfbi4prepp1",                                  anim = "_idle_garbage_man",  flag = 1, loop = true,
        prop = { model = "prop_cs_street_binbag_01", bone = 28422, pos = vector3(0.0, 0.04, -0.02), rot = vector3(0.0, 0.0, 0.0)    } },
    { name = "Caja Cerveza",      command = "beerbox",         dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "v_ret_ml_beerdus",      bone = 57005, pos = vector3(0.22, 0.0, 0.0),     rot = vector3(0.0, 266.0, 48.0)  } },
    { name = "Caja Cerveza 2",    command = "beerbox2",        dict = "move_weapon@jerrycan@generic",                   anim = "idle",               flag = 1, loop = true,
        prop = { model = "v_ret_ml_beeram",       bone = 57005, pos = vector3(0.22, 0.0, 0.0),     rot = vector3(0.0, 266.0, 48.0)  } },
    { name = "Ficha Policial",    command = "mugshot",         dict = "mp_character_creation@customise@male_a",         anim = "loop",               flag = 1, loop = true,
        prop = { model = "prop_police_id_board",  bone = 58868, pos = vector3(0.12, 0.24, 0.0),    rot = vector3(5.0, 0.0, 70.0)    } },
    { name = "Café",              command = "coffee",          dict = "amb@world_human_drinking@coffee@male@idle_a",    anim = "idle_c",             flag = 1, loop = true,
        prop = { model = "p_amb_coffeecup_01",    bone = 28422, pos = vector3(0.0, 0.0, 0.0),      rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Whiskey",           command = "whiskey",         dict = "amb@world_human_drinking@coffee@male@idle_a",    anim = "idle_c",             flag = 1, loop = true,
        prop = { model = "prop_drink_whisky",     bone = 28422, pos = vector3(0.01, -0.01, -0.06), rot = vector3(0.0, 0.0, 0.0)     } },
    { name = "Botella Whiskey",   command = "whiskeyb",        dict = "amb@world_human_drinking@beer@male@idle_a",      anim = "idle_a",             flag = 1, loop = true,
        prop = { model = "ba_prop_battle_whiskey_bottle_2_s", bone = 28422, pos = vector3(0.0, 0.0, 0.05), rot = vector3(0.0, 0.0, 0.0) } },
    { name = "Bartender Whiskey", command = "whiskeybartender",dict = "mini@drinking",                                  anim = "shots_barman_a",     flag = 1, loop = false,
        prop = { model = "ba_prop_battle_whiskey_bottle_2_s", bone = 28422, pos = vector3(0.05, -0.05, -0.05), rot = vector3(-60.0, 0.0, 0.0) } },
}

-- ============================================================
-- SENTARSE
-- ============================================================
Animations.sentarse = {
    { name = "Sentarse",          command = "sit",          dict = "anim@amb@business@bgen@bgen_no_work@",                anim = "sit_phone_phoneputdown_idle_nowork",      flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 2",        command = "sit2",         dict = "rcm_barry3",                                          anim = "barry_3_sit_loop",                        flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 3",        command = "sit3",         dict = "amb@lo_res_idles@",                                   anim = "world_human_picnic_male_lo_res_base",     flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 4",        command = "sit4",         dict = "amb@lo_res_idles@",                                   anim = "world_human_picnic_female_lo_res_base",   flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 5",        command = "sit5",         dict = "anim@heists@fleeca_bank@ig_7_jetski_owner",           anim = "owner_idle",                              flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 6",        command = "sit6",         dict = "timetable@jimmy@mics3_ig_15@",                        anim = "idle_a_jimmy",                            flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 7",        command = "sit7",         dict = "anim@amb@nightclub@lazlow@lo_alone@",                 anim = "lowalone_base_laz",                       flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 8",        command = "sit8",         dict = "timetable@jimmy@mics3_ig_15@",                        anim = "mics3_15_base_jimmy",                     flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 9",        command = "sit9",         dict = "amb@world_human_stupor@male@idle_a",                  anim = "idle_a",                                  flag = 1, loop = true,  prop = nil },
    { name = "Sentarse 10",       command = "sit10",        dict = "anim@scripted@bty2@ig1_hiding_target@male@",          anim = "hiding_sit",                              flag = 1, loop = true,  prop = nil },
    { name = "Sentarse Triste",   command = "sitsad",       dict = "anim@amb@business@bgen@bgen_no_work@",                anim = "sit_phone_phoneputdown_sleeping-noworkfemale", flag = 1, loop = true, prop = nil },
    { name = "Sentarse Lean",     command = "sitlean",      dict = "timetable@tracy@ig_14@",                              anim = "ig_14_base_tracy",                        flag = 1, loop = true,  prop = nil },
    { name = "Sentarse Lean 2",   command = "sitlean2",     dict = "anim@scripted@player@fix_astu_ig8_weed_smoke_v1@male@", anim = "male_pos_a_p2_base",                  flag = 1, loop = true,  prop = nil },
    { name = "Sentarse Lean 3",   command = "sitlean3",     dict = "anim@scripted@freemode@ig7_office_cell_floor@heeled@", anim = "base_pose_01",                          flag = 1, loop = true,  prop = nil },
    { name = "Asustado",          command = "sitscared",    dict = "anim@heists@ornate_bank@hostages@hit",                anim = "hit_loop_ped_b",                          flag = 1, loop = true,  prop = nil },
    { name = "Asustado 2",        command = "sitscared2",   dict = "anim@heists@ornate_bank@hostages@ped_c@",             anim = "flinch_loop",                             flag = 1, loop = true,  prop = nil },
    { name = "Asustado 3",        command = "sitscared3",   dict = "anim@heists@ornate_bank@hostages@ped_e@",             anim = "flinch_loop",                             flag = 1, loop = true,  prop = nil },
    { name = "Borracho",          command = "sitdrunk",     dict = "timetable@amanda@drunk@base",                         anim = "base",                                    flag = 1, loop = true,  prop = nil },
    { name = "Silla",             command = "sitchair",     dict = "timetable@ron@ig_3_couch",                            anim = "base",                                    flag = 1, loop = true,  prop = nil },
    { name = "Silla 2",           command = "sitchair2",    dict = "timetable@ron@ig_5_p3",                               anim = "ig_5_p3_base",                            flag = 1, loop = true,  prop = nil },
    { name = "Silla 3",           command = "sitchair3",    dict = "timetable@reunited@ig_10",                            anim = "base_amanda",                             flag = 1, loop = true,  prop = nil },
    { name = "Silla 4 - Lado",    command = "sitchair4",    dict = "timetable@ron@ron_ig_2_alt1",                         anim = "ig_2_alt1_base",                          flag = 1, loop = true,  prop = nil },
    { name = "Silla Piernas Cruz",command = "sitchair5",    dict = "timetable@jimmy@mics3_ig_15@",                        anim = "mics3_15_base_tracy",                     flag = 1, loop = true,  prop = nil },
    { name = "Silla Recostado",   command = "sitchair6",    dict = "timetable@maid@couch@",                               anim = "base",                                    flag = 1, loop = true,  prop = nil },
    { name = "Silla Atento",      command = "sitchair7",    dict = "anim@scripted@freemode_npc@fix_astu_ig3_pooh_jimmy@jimmy@", anim = "sit_base_jimmy",                  flag = 1, loop = true,  prop = nil },
    { name = "Silla Solo",        command = "sitchair8",    dict = "anim@scripted@freemode_npc@fix_dre_studio_entourage@", anim = "lonely_ballas",                         flag = 1, loop = true,  prop = nil },
    { name = "Baño",              command = "sittoilet",    dict = "anim@scripted@freemode@ig5_office_cell_seat@heeled@", anim = "base_pose_01",                            flag = 1, loop = true,  prop = nil },
    { name = "Baño 2",            command = "sittoilet2",   dict = "anim@scripted@cbr5@ig3_drill_box@pattern_01@lockbox_04@male@", anim = "idle",                          flag = 1, loop = true,  prop = nil },
    { name = "Codo Ventana",      command = "elbow",        dict = "anim@veh@lowrider@std@ds@arm@base",                   anim = "sit_low_lowdoor",                         flag = 1, loop = true,  prop = nil },
    { name = "Abdominales",       command = "situp",        dict = "amb@world_human_sit_ups@male@idle_a",                 anim = "idle_a",                                  flag = 1, loop = true,  prop = nil },
}
